# Crowdin Configuration for SGEX Workbench
# https://crowdin.com/

project_id: "sgex-workbench"
api_token_env: "CROWDIN_API_TOKEN"
base_path: "."
base_url: "https://api.crowdin.com"

preserve_hierarchy: true

files:
  # Source file (English)
  - source: /src/locales/en_US/translation.json
    translation: /src/locales/%two_letters_code%_%two_letters_code_upper%/translation.json
    languages_mapping:
      two_letters_code:
        fr: fr
        es: es
      two_letters_code_upper:
        fr: FR
        es: ES

  # Alternative: .po files support
  # - source: /locales/templates/template.pot
  #   translation: /src/locales/%two_letters_code%_%two_letters_code_upper%/translation.po
  #   languages_mapping:
  #     two_letters_code:
  #       fr: fr
  #       es: es
  #     two_letters_code_upper:
  #       fr: FR
  #       es: ES

# Upload options
upload_translations: true
upload_sources: true
auto_update: true

# Export options
export_only_approved: false
skip_untranslated_strings: false
skip_untranslated_files: false
export_approved_only: false

# Translation memory
translation_memory:
  project_id: "sgex-workbench"