name: Blank Issue
description: Create a blank issue without pre-filled fields
title: ""
labels: ["blank-issue"]
body:
  - type: markdown
    attributes:
      value: |
        Please describe your issue below. You can use any format you prefer.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your issue, feedback, or question
      placeholder: Enter your description here...
    validations:
      required: false