blank_issues_enabled: true
contact_links:
  - name: WHO SMART Guidelines Support
    url: mailto:smart@who.int
    about: Email the WHO SMART Guidelines team directly for urgent issues or questions
  - name: SGEX Documentation
    url: https://litlfred.github.io/sgex/docs/overview
    about: View comprehensive documentation and user guides