name: DAK Question
description: Ask questions about implementing or using this Digital Adaptation Kit (DAK)
title: "[DAK Question]: "
labels: ["question", "dak-question"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for asking a question about this Digital Adaptation Kit (DAK)!

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know about this DAK?
    validations:
      required: true

  - type: dropdown
    id: question-category
    attributes:
      label: Question Category
      description: What aspect of the DAK is your question about?
      options:
        - Implementation Guidance
        - Clinical Workflows
        - Technical Integration
        - FHIR Resource Usage
        - Terminology/Coding
        - Configuration/Setup
        - Testing/Validation
        - General Understanding
        - Other
    validations:
      required: true

  - type: textarea
    id: implementation-context
    attributes:
      label: Implementation Context
      description: What is your implementation scenario or use case?
    validations:
      required: false

  - type: textarea
    id: attempted-solutions
    attributes:
      label: What have you tried?
      description: Have you attempted any approaches or reviewed documentation?
    validations:
      required: false

  - type: textarea
    id: specific-challenge
    attributes:
      label: Specific Challenge
      description: What specific challenge or blocker are you facing?
    validations:
      required: false