name: DAK Bug Report
description: Report a bug or issue with this specific Digital Adaptation Kit (DAK)
title: "[DAK Bug]: "
labels: ["bug", "dak-issue"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug in this Digital Adaptation Kit (DAK)!

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: What is the issue with this DAK?
    validations:
      required: true

  - type: dropdown
    id: dak-component
    attributes:
      label: DAK Component
      description: Which DAK component is affected?
      options:
        - Business Processes (BPMN)
        - Decision Support Logic (DMN)
        - Indicators & Measures
        - Data Entry Forms
        - Terminology (Code Systems/Value Sets)
        - FHIR Profiles
        - FHIR Extensions
        - Test Data & Examples
        - Other
    validations:
      required: true

  - type: textarea
    id: expected-vs-actual
    attributes:
      label: Expected vs Actual Behavior
      description: What should happen versus what actually happens?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can this issue be reproduced?
      placeholder: |
        1. Go to...
        2. Click on...
        3. Observe...
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: How does this affect DAK implementation or clinical workflows?
    validations:
      required: false