name: Documentation Issue
description: Report problems or improvements needed in documentation
title: "[Documentation]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve the SGEX Workbench documentation!

  - type: textarea
    id: issue-description
    attributes:
      label: Documentation Issue
      description: What's wrong with the current documentation?
    validations:
      required: true

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - User Guide / Help Content
        - API Documentation
        - README / Getting Started
        - Code Comments
        - Other
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How should this be improved or what should be added?
    validations:
      required: false

  - type: input
    id: location
    attributes:
      label: Location
      description: Where did you encounter this documentation issue? (URL, file path, etc.)
    validations:
      required: false