name: Feature Request for SGeX
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["feature request"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see added and why it would be useful.
      placeholder: Please provide a clear description of the feature you're requesting...
    validations:
      required: true