name: Question
description: Ask for help or clarification about SGEX Workbench
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for asking a question! We're here to help.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What were you trying to do when this question came up?
    validations:
      required: false

  - type: textarea
    id: attempted
    attributes:
      label: What have you tried?
      description: Have you attempted any solutions or looked anywhere for answers?
    validations:
      required: false