name: Generate Service Table

# This workflow automatically generates the service table documentation
# from the codebase and commits it back to the repository.
# 
# INFINITE LOOP PREVENTION:
# 1. Job condition excludes commits made by github-actions[bot]
# 2. Job condition excludes commits with "Auto-update service table" message  
# 3. Path filters exclude the generated files from triggering the workflow

permissions:
  contents: write
  actions: read

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/dak/faq/questions/**'
      - 'services/**'
      - 'scripts/generate-service-table.js'
      - 'package.json'
      # Exclude generated files to prevent infinite loops
      - '!docs/SERVICE_TABLE.md'
      - '!services/dak-faq-mcp/schemas/questionId.schema.json'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/dak/faq/questions/**'
      - 'services/**'
      - 'scripts/generate-service-table.js'

jobs:
  generate-service-table:
    runs-on: ubuntu-latest
    # Skip if the commit was made by the GitHub Action itself to prevent infinite loops
    if: github.actor != 'github-actions[bot]' && !contains(github.event.head_commit.message, 'Auto-update service table')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.head_ref || github.ref_name }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate service table
      run: npm run generate-service-table

    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions[bot]"
        git add docs/SERVICE_TABLE.md
        git add services/dak-faq-mcp/schemas/questionId.schema.json
        git commit -m "Auto-update service table and question ID schema

        - Generated service table from current codebase
        - Updated FAQ question ID enum with ${count} questions
        - Links to schemas and OpenAPI specs updated
        
        Generated by: scripts/generate-service-table.js
        Timestamp: $(date -Iseconds)" || exit 0
        git push origin HEAD:${{ github.head_ref || github.ref_name }}