name: Deploy Landing Page

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/qa-report.html'
      - 'public/docs/qa-report.html'
      - 'docs/github-issues-analysis.md'
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Branch to use for build scripts (defaults to deploy branch)'
        required: false
        default: 'deploy'

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "landing-page-deploy"
  cancel-in-progress: false

jobs:
  deploy-landing-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deploy branch (or fallback to main)
        uses: actions/checkout@v4
        with:
          ref: main  # Use main branch since deploy branch doesn't exist yet
          fetch-depth: 0  # Fetch full history for gh-pages branch

      - name: Configure git user
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci

      - name: Build React landing page application
        shell: bash
        run: |
          set -e
          
          echo "Building React landing page application..."
          
          # Build the React app
          npm run build
          
          # Verify build output exists
          if [[ ! -f "build/index.html" ]]; then
            echo "ERROR: React build failed - index.html not found in build output"
            exit 1
          fi
          
          echo "✅ React landing page build completed successfully"
          echo "Build contents:"
          ls -la build/

      - name: Deploy to gh-pages root (preserving existing branches)
        shell: bash
        run: |
          set -e
          
          # Save the React app build
          echo "Preserving React app build..."
          mkdir -p /tmp/landing-build
          cp -a build/. /tmp/landing-build/
          
          # Checkout gh-pages branch
          if git show-ref --verify --quiet refs/remotes/origin/gh-pages; then
            echo "Checking out existing gh-pages branch"
            git stash -u -m "Stash before gh-pages checkout" || echo "Nothing to stash"
            git clean -fd -e node_modules
            git checkout gh-pages
          else
            echo "Creating new gh-pages branch"
            git checkout --orphan gh-pages
            git rm -rf .
            echo "# GitHub Pages" > README.md
            git add README.md
            git commit -m "Initial gh-pages branch"
            git push origin gh-pages
          fi
          
          # CRITICAL: Only remove files, NEVER remove directories (to preserve branch builds)
          echo "Removing only root-level files (preserving all branch directories)..."
          
          # List what directories exist for safety verification
          echo "Existing directories before cleanup:"
          ls -la */ 2>/dev/null || echo "No directories found"
          
          # Remove only specific files that could conflict with landing page
          rm -f index.html
          rm -f manifest.json  
          rm -f asset-manifest.json
          rm -f service-worker.js
          rm -f robots.txt
          rm -f favicon.ico
          rm -f logo*.png
          rm -f README.md
          rm -f package.json
          rm -f package-lock.json
          
          # Remove static directory only if it exists at root (not in branch subdirs)
          if [[ -d "static" ]]; then
            echo "Removing root static directory..."
            rm -rf static
          fi
          
          # Deploy landing page to root (this will not affect any subdirectories)
          echo "Deploying React app to root..."
          cp -a /tmp/landing-build/. .
          
          # Verify existing directories are still there
          echo "Directories after deployment:"
          ls -la */ 2>/dev/null || echo "No directories found"
          
          # Clean up temporary build
          rm -rf /tmp/landing-build
          
          echo "✅ React app deployed to gh-pages root while preserving all branch directories"

      - name: Commit and push changes
        shell: bash
        run: |
          set -e
          
          # Verify we're on gh-pages branch
          current_branch=$(git branch --show-current)
          if [[ "$current_branch" != "gh-pages" ]]; then
            echo "ERROR: Not on gh-pages branch! Current branch: $current_branch"
            exit 1
          fi
          
          # Stage all changes
          git add -A
          
          # Check if there are changes to commit
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            echo "Committing landing page deployment..."
            
            # Determine deployment type for commit message
            if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
              deployment_type="manual"
              trigger_info="Triggered from deploy branch"
            else
              deployment_type="automatic"
              trigger_info="Auto-triggered by push to main"
            fi
            
            git commit -m "🏠 Deploy React landing page (${deployment_type})

            - Updated with React app build from main branch
            - ${trigger_info}
            - Deployed at $(date -u '+%Y-%m-%d %H:%M:%S UTC')
            - Commit: ${{ github.sha }}"
            
            echo "Pushing to gh-pages..."
            git pull origin gh-pages --rebase || echo "Pull failed, attempting to push anyway..."
            git push origin gh-pages
            
            echo "✅ React landing page deployment completed successfully"
          fi

      - name: Output deployment info
        shell: bash
        run: |
          landing_url="https://litlfred.github.io/sgex/"
          
          # Determine deployment type for output message
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            deployment_type="Manual"
            trigger_info="Triggered from deploy branch"
          else
            deployment_type="Automatic"
            trigger_info="Auto-triggered by push to main"
          fi
          
          echo "🏠 React Landing Page Deployment Summary:"
          echo "- Landing Page URL: $landing_url"
          echo "- Deployment Type: $deployment_type"
          echo "- $trigger_info"
          echo "- Deployed at: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          echo "- Source Branch: ${{ github.event.inputs.source_branch || 'deploy' }}"
          echo "- Commit: ${{ github.sha }}"